/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsuper_utils_Console */

#ifndef _Included_jsuper_utils_Console
#define _Included_jsuper_utils_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsuper_utils_Console
 * Method:    readRawInput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jsuper_utils_Console_readRawInput
  (JNIEnv *, jclass);

/*
 * Class:     jsuper_utils_Console
 * Method:    init
 * Signature: ()Ljava/io/PrintStream;
 */
JNIEXPORT jobject JNICALL Java_jsuper_utils_Console_init
  (JNIEnv *, jobject);

/*
 * Class:     jsuper_utils_Console
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsuper_utils_Console_close
  (JNIEnv *, jobject);

/*
 * Class:     jsuper_utils_Console
 * Method:    focus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsuper_utils_Console_focus
  (JNIEnv *, jobject);

/*
 * Class:     jsuper_utils_Console
 * Method:    getCursorPosition
 * Signature: ()Ljsuper/utils/Coordinate;
 */
JNIEXPORT jobject JNICALL Java_jsuper_utils_Console_getCursorPosition
  (JNIEnv *, jobject);

/*
 * Class:     jsuper_utils_Console
 * Method:    getConsoleSize
 * Signature: ()Ljsuper/utils/Coordinate;
 */
JNIEXPORT jobject JNICALL Java_jsuper_utils_Console_getConsoleSize
  (JNIEnv *, jobject);

/*
 * Class:     jsuper_utils_Console
 * Method:    getStartCoordinate
 * Signature: ()Ljsuper/utils/Coordinate;
 */
JNIEXPORT jobject JNICALL Java_jsuper_utils_Console_getStartCoordinate
  (JNIEnv *, jobject);

/*
 * Class:     jsuper_utils_Console
 * Method:    setCursorPosition
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_jsuper_utils_Console_setCursorPosition
  (JNIEnv *, jobject, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
