/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ssuper_utils_Console */

#ifndef _Included_ssuper_utils_Console
#define _Included_ssuper_utils_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ssuper_utils_Console
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ssuper_utils_Console_init
  (JNIEnv *, jobject);

/*
 * Class:     ssuper_utils_Console
 * Method:    setCursorPosition
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_ssuper_utils_Console_setCursorPosition
  (JNIEnv *, jobject, jshort, jshort);

/*
 * Class:     ssuper_utils_Console
 * Method:    getCursorPosition
 * Signature: ()Lssuper/utils/Console/CursorPosition;
 */
JNIEXPORT jobject JNICALL Java_ssuper_utils_Console_getCursorPosition
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
