/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Ssuper_utils_Console */

#ifndef _Included_Ssuper_utils_Console
#define _Included_Ssuper_utils_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Ssuper_utils_Console
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Ssuper_utils_Console_init
  (JNIEnv *, jobject);

/*
 * Class:     Ssuper_utils_Console
 * Method:    setCursorPosition
 * Signature: (SS)V
 */
JNIEXPORT void JNICALL Java_Ssuper_utils_Console_setCursorPosition
  (JNIEnv *, jobject, jshort, jshort);

#ifdef __cplusplus
}
#endif
#endif
